language: python
python:
  - '2.7'
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - nosetests
deploy:
  provider: pypi
  user: lord_business
  password:
    secure: F5vXa0in9u/9WRzXLhfFyHEA4JEs9YGspwaori3hoxo6C6OvxyFCDzkQyiaAKTQn7dtHfy+aRgtBhujfplWr/8//td6836ShEryT4wic1sAPg0kEOJslZcIgROKHx882ekbK7x492gd3g/DCb9f9+wjEa6Np8UEby/O9MDAZlvJyv5+AA5EuIXzC2Yjp4bYSzuffeeERjZzwCH4DSbpungcROYoG47OjY7T2xS1LnsGl7jkclL8NTxpBak4snS+vWELUm0S4Jg+B4MJqYLWsDK7l0ZeLugLF62lmY8C0L0B7+8Lf5l0lVntS7D8K+jzHCIjok2bRv6tl6LoYfBnGqRtLNLYY2G6sLQ5/RAIDfuNni76f8Oa95pqulRbg411S78M20fdJJk5T+JQ6IgiH0PIth9VUwFdUj6YQ2tcdABIyjDvKMU46XP5sOt7Nyxya07u5Vm6ElvVOjkKFI0p+4ODBW2RS2a+dECOeKNzdDjxzWoNQXz0sbzEMFANb5ogfWYD92RnbMbZuBk15M5Hj8r2YFzvfl4iSztqY+LHkk+u7eheLC3S6sXjH8AHYTkasgAimFFBoZpo3gW+SKo7gTqTApcMXoVl34RuN0m9gqetzIAs7S0Z3VCBFtIrKEM6Wa8pTQ+RuO5Mq1OPynAoxEiyGUpDPJrEMpeUUxKJEiyY=
  on:
    tags: true
    branch: master
